version: '3'

services:
  node1:
    build:
      context: ./simpleServer
    networks:
      - mynetwork

  node2:
    build:
      context: ./simpleServer
    networks:
      - mynetwork

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
